version: "3.9"

networks:
  intern:
    name: intern
    external: true

services:

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - intern

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 4000:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - intern
